connector:
    name: Akeneo Mass Edit Connector
    jobs:
        update_product_value:
            title: update_product_value
            type:  mass_edit
            steps:
                perform:
                    title: update_product_value
                    services:
                        reader:    pim_enrich.mass_edit.update_product_value.reader
                        processor: pim_enrich.mass_edit.update_product_value.processor
                        writer:    pim_base_connector.writer.doctrine.product
        add_product_value:
            title: add_product_value
            type:  mass_edit
            steps:
                perform:
                    title: add_product_value
                    services:
                        reader:    pim_enrich.mass_edit.add_product_value.reader
                        processor: pim_enrich.mass_edit.add_product_value.processor
                        writer:    pim_base_connector.writer.doctrine.product
