parameters:
    pim_enrich.repository.sequential_edit.class: Pim\Bundle\EnrichBundle\Entity\Repository\SequentialEditRepository
    pim_enrich.repository.mass_edit.class:       Pim\Bundle\EnrichBundle\Entity\Repository\MassEditRepository

services:
    pim_enrich.repository.sequential_edit:
        class: %pim_enrich.repository.sequential_edit.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_enrich.entity.sequential_edit.class%]
        tags:
            - { name: 'pim_repository' }

    pim_enrich.repository.mass_edit:
        class: %pim_enrich.repository.mass_edit.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [%pim_enrich.entity.mass_edit.job_configuration.class%]
        tags:
            - { name: 'pim_repository' }
